import{useEffect,useRef,useState}from"react";
type Q={c:string;q:string;o:string[];a:number;e:string};
const qs:Q[]=[["Math","What is 12 × 8?",["86","96","108","112"],1,"12 × 8 = 96."],["Science","Which planet is known as the Red Planet?",["Venus","Mars","Jupiter","Mercury"],1,"Mars is known for its reddish appearance."],["Geography","Ghana is on which continent?",["Asia","Africa","Europe","Oceania"],1,"Ghana is in West Africa."],["History","The pyramids at Giza were built in…",["Ancient Egypt","Rome","Mali","Aztec Empire"],0,"The Giza pyramids were built in ancient Egypt."],["Technology","What does CPU stand for?",["Central Processing Unit","Computer Power Utility","Core Program Unit","Central Program User"],0,"CPU means Central Processing Unit."],["Logic","All racers are players. Kofi is a racer. Kofi is a…",["Teacher","Player","Track","Car"],1,"Therefore Kofi is a player."],["African Knowledge","Timbuktu is in present-day…",["Ghana","Mali","Kenya","Ethiopia"],1,"Timbuktu is in Mali."],["Ghana Knowledge","What is Ghana's capital?",["Kumasi","Cape Coast","Accra","Tamale"],2,"Accra is the capital."],["Crypto & Blockchain","BTC refers to…",["Bitcoin","Blockchain Transfer Credit","Base Token Coin","Bitcoin Transaction Chain"],0,"BTC is Bitcoin's common ticker."],["Crypto & Blockchain","A blockchain is best described as…",["An internet cable","A distributed ledger","A password manager","A monitor"],1,"A blockchain is a distributed ledger."],["Crypto & Blockchain","Market cap is commonly…",["Price × circulating supply","Price ÷ supply","Daily volume only","Wallet count"],0,"Market cap is price multiplied by circulating supply."]].map(x=>({c:x[0] as string,q:x[1] as string,o:x[2] as string[],a:x[3] as number,e:x[4] as string}));
const KEY="cyro-v2";
const upgrades=[{name:"Street",cost:0,mult:1},{name:"Sprint",cost:250,mult:1.08},{name:"Nitro",cost:750,mult:1.18}];
export default function App(){const[p,setP]=useState<"home"|"race"|"result"|"settings">("home"),[xp,setXp]=useState(()=>+localStorage.getItem(KEY+"xp")||0),[coins,setCoins]=useState(()=>+localStorage.getItem(KEY+"coins")||0),[car,setCar]=useState(()=>+localStorage.getItem(KEY+"car")||0),[cat,setCat]=useState(()=>localStorage.getItem(KEY+"cat")||"ALL"),[speed,setSpeed]=useState(45),[dist,setDist]=useState(0),[score,setScore]=useState(0),[q,setQ]=useState<Q|null>(null),[t,setT]=useState(30),[pick,setPick]=useState<number|null>(null),[msg,setMsg]=useState(""),run=useRef(false),cv=useRef<HTMLCanvasElement>(null);
useEffect(()=>{localStorage.setItem(KEY+"xp",String(xp));localStorage.setItem(KEY+"coins",String(coins));localStorage.setItem(KEY+"car",String(car));localStorage.setItem(KEY+"cat",cat)},[xp,cat]);
useEffect(()=>{if(p!=="race")return;run.current=!q;let id=0,last=performance.now();const loop=(n:number)=>{const d=Math.min(.05,(n-last)/1000);last=n;if(run.current){setSpeed(v=>Math.min(100,v+1*d));setDist(v=>v+speed*d*.12);setScore(v=>v+Math.round(speed*d))}draw();id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);return()=>cancelAnimationFrame(id)},[p,q,speed]);
useEffect(()=>{if(!q)return;setT(30);const id=setInterval(()=>setT(v=>{if(v<=1){clearInterval(id);answer(-1);return 0}return v-1}),1000);return()=>clearInterval(id)},[q]);
function draw(){const c=cv.current;if(!c)return;const d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;const x=c.getContext("2d")!;x.setTransform(d,0,0,d,0,0);x.fillStyle="#071019";x.fillRect(0,0,w,h);x.fillStyle="#252b33";x.beginPath();x.moveTo(w*.22,h);x.lineTo(w*.42,h*.18);x.lineTo(w*.58,h*.18);x.lineTo(w*.78,h);x.fill();x.strokeStyle="#66707d";x.setLineDash([18,22]);for(const z of[.4,.5,.6]){x.beginPath();x.moveTo(w*z,h);x.lineTo(w*(.5+(z-.5)*.2),h*.18);x.stroke()}x.setLineDash([]);x.fillStyle="#63e6be";x.fillRect(w/2-24,h*.72-42,48,72);x.fillStyle="#0a1017";x.fillRect(w/2-17,h*.72-29,34,18);x.fillStyle="#fff";x.font="800 12px system-ui";x.textAlign="center";x.fillText(Math.round(speed)+" KM/H",w/2,h*.72+48)}
function start(){setP("race");setRun();setSpeed(45);setDist(0);setScore(0);setQ(null);setPick(null);setMsg("")}function setRun(){run.current=true}
function challenge(){const a=qs.filter(x=>cat==="ALL"||x.c===cat);setQ(a[Math.floor(Math.random()*a.length)]);run.current=false}
function answer(i:number){if(!q||pick!==null)return;setPick(i);const good=i===q.a;if(good){setSpeed(v=>Math.min(100,v+25));setScore(v=>v+Math.round(500*upgrades[car].mult));setXp(v=>v+100);setCoins(v=>v+25);setMsg("CORRECT • BOOST +25")}else{setSpeed(v=>Math.max(10,v-15));setXp(v=>v+20);setMsg(i<0?"TIME UP • SPEED -15":"WRONG • SPEED -15")}setTimeout(()=>{setQ(null);setPick(null);setMsg("");run.current=true},1100)}
const cats=["ALL",...Array.from(new Set(qs.map(x=>x.c)))];
return <main><header><b>CYRO<span>.</span></b><small>RACE. THINK. LEARN.</small><label>XP {xp} · 🪙 {coins}</label></header>
{p==="home"&&<section className="home"><i>NO LOGIN · LOCAL PROGRESS</i><h1>Race your<br/><em>brain.</em></h1><p>Simple racing. Real questions. Every challenge gives you <strong>30 seconds</strong>.</p><button className="go" onClick={start}>START RACE →</button><button onClick={()=>setP("garage")}>GARAGE</button><button onClick={()=>setP("settings")}>SETTINGS</button><div className="tiles"><div><b>30s</b><small>per challenge</small></div><div><b>{qs.length}</b><small>starter challenges</small></div><div><b>9+</b><small>knowledge areas</small></div></div></section>}
{p==="race"&&<section className="race"><div className="hud"><span>DISTANCE<b>{Math.floor(dist)}m</b></span><span>SCORE<b>{score}</b></span><span>SPEED<b>{Math.round(speed)}</b></span><button onClick={()=>{setP("result");run.current=false}}>FINISH</button></div><canvas ref={cv}/><div className="controls"><button onClick={()=>setSpeed(v=>Math.min(100,v+5))}>▲</button><button className="go" onClick={challenge}>🧠 CHALLENGE</button><button onClick={()=>setSpeed(v=>Math.max(10,v-5))}>▼</button></div>{q&&<div className="overlay"><div className="card"><div className="top"><i>{q.c}</i><b className={t<=5?"danger":""}>00:{String(t).padStart(2,"0")}</b></div><h2>{q.q}</h2><div className="choices">{q.o.map((o,i)=><button disabled={pick!==null} className={pick===i?"picked":""} onClick={()=>answer(i)} key={o}>{String.fromCharCode(65+i)} <span>{o}</span></button>)}</div>{msg&&<strong className="feedback">{msg}</strong>}<p>{pick!==null?q.e:"30 seconds. Choose carefully."}</p></div></div>}</section>}
{p==="result"&&<section className="home"><i>RACE COMPLETE</i><h1>Nice<br/><em>run.</em></h1><div className="result"><div>SCORE<b>{score}</b></div><div>XP<b>+{Math.round(score/5)}</b></div><div>DISTANCE<b>{Math.floor(dist)}m</b></div></div><button className="go" onClick={start}>RACE AGAIN →</button><button onClick={()=>setP("home")}>HOME</button></section>}
{p==="garage"&&<section className="settings"><i>GARAGE</i><h1>Build your<br/><em>ride.</em></h1><div className="result">{upgrades.map((u,i)=><div key={u.name}><b>{u.name}</b><small>{i===0?"Starter":`+${Math.round((u.mult-1)*100)}% score`}</small><button disabled={car===i||coins<u.cost} onClick={()=>{setCar(i);if(i>0)setCoins(v=>v-u.cost)}}>{car===i?"EQUIPPED":`🪙 ${u.cost}`}</button></div>)}</div><button onClick={()=>setP("home")}>← BACK</button></section>}
{p==="settings"&&<section className="settings"><i>SETTINGS</i><h1>Choose your<br/><em>knowledge.</em></h1><label>QUESTION CATEGORY<select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><p>Progress is saved locally. No account or login is required.</p><button onClick={()=>setP("home")}>← BACK</button></section>}</main>}