create table if not exists public.knowledge_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  source_url text,
  country text,
  created_at timestamptz not null default now()
);

create table if not exists public.research_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  title text,
  created_at timestamptz not null default now()
);

create table if not exists public.research_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.research_sessions(id) on delete cascade,
  role text not null check (role in ('user','cyro','system')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.knowledge_documents enable row level security;
alter table public.research_sessions enable row level security;
alter table public.research_messages enable row level security;

create policy "public knowledge readable"
  on public.knowledge_documents for select
  using (true);

create policy "users manage own sessions"
  on public.research_sessions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users manage own messages"
  on public.research_messages for all
  using (
    exists (
      select 1 from public.research_sessions s
      where s.id = research_messages.session_id
      and s.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.research_sessions s
      where s.id = research_messages.session_id
      and s.user_id = auth.uid()
    )
  );
